### ISSUE TITLE
remove or update section `Revisions`

### ISSUE THREAD

**Issue by timmwille** [osegermany/git-internals-doc#2]
Maybe it is best to link to the source instead or to releases?

**Comment by hoijui** [comment]
I can easily link to the sources, but I am not sure how much that helps.
The releases would just be a page with zips of the source (even less useful),
because I will not try to generate the PDFs for all the old versions again. that would be a lot of work.

Proposal:

1. I add links to the sources to all the revisions (aka releases on github)
2. To the last revision released (2013) before we took over, I will add the respective PDF to the release page on github manually and link to it from the revisions page from that specific revision.
3. for all the newer releases we will do, I will try to add links to PDFs

k? 

... I could just add the link last PDF from 2013 to the respective revision

**Comment by hoijui** [comment]
ah ... just now saw you also asked if it should maybe be removed.. and yes, that is even better I think!
thanks timm!
I might keep it and just add a link to the github releases page of the project (and to the old repos PDF).
